### PR TITLE
Add blacklisting of resource types

### LINKED ISSUE #174: [Suggestion] Allow disabling specific resources in the config
Would be good to have an option to whitelist/blacklist which resource types can be transferred by SFM for modpack balancing purposes

### PR DESCRIPTION
**Pull request by Burkino**
Adds a simple config option to blacklist resource types
Might eventually need to be expanded to support namespaces other than sfm, or specific resources (ie mekanism spent waste)

Closes #174

### CODE REVIEW

**Comment by TeamDman** [comment]
nitpick: pls use disallowed/disabled instead of blacklist verbiage

**Comment by Snow-ctrl-c** [comment]
Issue https://github.com/TeamDman/SuperFactoryManager/issues/174 references resource types not specific items/fluids/etc.

**Comment by Snow-ctrl-c** [comment]
Restricting specific items/fluids/etc would also mean that not all code will work in every pack and would require users to compare shared code with the pack's specific config. Makes more sense as a feature in an add-on mod to me.

**Comment by TeamDman** [comment]
having a config to restrict resource types is fine.
lets leave restricting specific resources for a separate PR.
I imagine the only candidate would be mekanism waste.

Since the introduction of configs for minimum tick intervals there has been a need for previewing the server config in the manager gui, adding resource type restrictions just adds to that need

**Pull request merged**
